baseURL = 'https://thecreatingchild.com/'
languageCode = 'en-us'
title = 'The Creating Child'
theme = 'ananke'

[params]
  custom_css = ["custom.css"]
  mainSections = ["Posts"]
  recent_posts_number = 5

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 20

#  [[menu.main]]
#    name = "Notes"
#    url = "/notes/"
#    weight = 10

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10