baseURL = 'https://thecreatingchild.com/'
languageCode = 'en-us'
title = 'The Creating Child'
theme = 'ananke'

[params]
  custom_css = ["custom.css"]

[menu]
  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10